export interface StyleProps {
    isNotifier?: boolean;
    isSuccess?: boolean;
    isBar?: boolean;
    isSideBar?: boolean;
    padding?: string;
    size?: string;
    percentage?: string;
    strokeWidth?: string;
    bgColor?: string,
    barBgColor?: string,
    barOffset?: string,
    barFontSize?: string,
    width?: string,
    height?: string,
    rightMargin?: string,
    leftMargin?: string,
    radius?: string,
    color?: string,
    fontWeight?: string,
    topMargin?: string,
    bottomMargin?: string,
    hoverBgColor?: string,
    margin?: string,
    sizeUnit?: string,
    borderType?: string,
    zIndex?: string,
    titleSize?: string,
    textSize?: string,
    titleColor?: string,
    titleWeight?: string,
    topPadding?: string,
    bottomPadding?: string,
    leftPadding?: string,
    rightPadding?: string, 
    token?: string,
    justifyContent?: string,
    alignItems?: string,
    align?: string,
    borderColor?: string,
    hoverColor?: string;
    wrap?: string,
    isMaxWidth?: boolean,
    top?: string,
    right?: string,
    left?: string,
    bottom?: string,
    decoration?: string,
    type?: string, 
    isPicked?: boolean,
    hasBottomBorder?: boolean,
    display?: string
}